import { afterEach, expect, jest, test } from '@jest/globals';
import { act, fireEvent, render, screen } from '@testing-library/react-native';
import { fetch } from 'expo/fetch';
import { Alert } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Trips from '../../app/trips';
import * as media from '../trip-media';
import * as tripApi from '../trip-api';
import { StoreProvider } from '../store';
import { TripsProvider } from '../trip-store';
import { tripStorageKey } from '../trips';
jest.mock('@react-native-async-storage/async-storage', () => ({ getItem: jest.fn(async () => null), setItem: jest.fn(async () => {}) }));
jest.mock('react-native-safe-area-context', () => ({ useSafeAreaInsets: () => ({ top: 0, bottom: 0, left: 0, right: 0 }) }));
jest.mock('react-native-view-shot', () => ({ captureRef: jest.fn() }));
jest.mock('expo-media-library', () => ({}));
jest.mock('expo-file-system', () => ({ Paths: { document: 'file:///test' }, Directory: class { uri = 'file:///test'; }, File: class {} }));
jest.mock('expo-video', () => ({ useVideoPlayer: jest.fn(() => ({pause:jest.fn(),replaceAsync:jest.fn(async () => {})})), VideoView: () => null }));
jest.mock('expo/fetch', () => ({ fetch: jest.fn() }));
const previousAuth = process.env.EXPO_PUBLIC_AUTH_ENABLED;
afterEach(() => { process.env.EXPO_PUBLIC_AUTH_ENABLED = previousAuth; jest.restoreAllMocks(); });
test('traveller creates a trip, adds a timed meal and reopens the saved calendar', async () => {
 process.env.EXPO_PUBLIC_AUTH_ENABLED = 'false';
 jest.mocked(fetch).mockResolvedValue({ ok: true, status: 200, json: async () => [{ placeId:'kyoto', name:'Kyoto', label:'Kyoto, Japan', countryCode:'JP', country:'Japan' }] } as Awaited<ReturnType<typeof fetch>>);
 await render(<StoreProvider accountId="traveller"><TripsProvider accountId="traveller"><Trips /></TripsProvider></StoreProvider>);
 expect(await screen.findByRole('header', {name: 'A little planning. A great adventure.'})).toBeTruthy();
 expect(screen.queryByRole('button', {name: 'New trip'})).toBeNull();
 await fireEvent.press(screen.getByRole('button', { name: 'Plan my first trip' }));
 await fireEvent.changeText(screen.getByLabelText('Trip name'), 'Kyoto memories');
 await fireEvent.press(screen.getByRole('button', { name: 'Departure date: Choose a date' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Next year' }));
 const future = new Date(new Date().getFullYear() + 1, new Date().getMonth(), 15, 12);
 await fireEvent.press(screen.getByRole('button', { name: future.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) }));
 await fireEvent.changeText(screen.getByLabelText('Destination'), 'Kyoto');
 await fireEvent.press(await screen.findByRole('button', { name: 'Kyoto, Japan' }));
 await fireEvent.changeText(screen.getByLabelText('Days at destination 1'), '3');
 await fireEvent.press(screen.getByRole('button', { name: 'Add another destination' }));
 jest.mocked(fetch).mockResolvedValue({ ok: true, status: 200, json: async () => [{ placeId:'osaka', name:'Osaka', label:'Osaka, Japan', countryCode:'JP', country:'Japan' }] } as Awaited<ReturnType<typeof fetch>>);
 await fireEvent.changeText(screen.getByLabelText('Destination 2'), 'Osaka');
 await fireEvent.press(await screen.findByRole('button', { name: 'Osaka, Japan' }));
 await fireEvent.changeText(screen.getByLabelText('Days at destination 2'), '2');
 await fireEvent.press(screen.getByRole('button', { name: 'Currency: USD · US Dollar' }));
 await fireEvent.changeText(screen.getByLabelText('Search Currency'), 'yen');
 await fireEvent.press(screen.getByRole('button', { name: 'JPY · Japanese Yen' }));
 await fireEvent.changeText(screen.getByLabelText('Travellers (1–12)'), '3');
 await fireEvent.press(screen.getByRole('button', { name: 'Trip style, food & luggage' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Family' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Halal' }));
 await fireEvent.changeText(screen.getByLabelText('Children included in your travellers'), '1');
 await fireEvent.changeText(screen.getByLabelText('Bags for the whole group (0–24)'), '2');
 await fireEvent.changeText(screen.getByLabelText('Things you love'), 'Gardens');
 await fireEvent.press(screen.getByRole('button', { name: 'Create my trip' }));
 expect(await screen.findByRole('header', { name: 'Kyoto memories' })).toBeTruthy();
 expect(screen.getByText('Kyoto → Osaka')).toBeTruthy();
 const secondDay = screen.getByRole('button', { name: /^Day 2,/ });
 await fireEvent.press(secondDay);
 expect(secondDay.props.accessibilityState.selected).toBe(true);
 await fireEvent.press(screen.getByRole('button', { name: /^Day 1,/ }));
 await fireEvent.press(screen.getByRole('tab', { name: 'Memories' }));
 expect(await screen.findByRole('button', { name: 'Choose photos' })).toBeTruthy();
 jest.spyOn(media, 'choosePhotos').mockResolvedValue([{id:'photo-1',uri:'file:///photo.jpg',width:100,height:100,caption:'A memory',creationTime:0}]);
 jest.spyOn(media, 'photoData').mockResolvedValue([{data:'YWJj',caption:'A memory'}]);
 jest.spyOn(tripApi, 'memoryCapabilities').mockResolvedValue({editorVersion:1,maxAudioBytes:3000000});
 const discard = jest.spyOn(media, 'discardVideo').mockImplementation(() => {});
 let finishRender!: (bytes: Awaited<ReturnType<typeof tripApi.renderMemory>>) => void;
 const renderVideo = jest.spyOn(tripApi, 'renderMemory').mockImplementation(() => new Promise(resolve => { finishRender = resolve; }));
 jest.spyOn(media, 'saveVideo').mockReturnValue('file:///memory.mp4');
 await fireEvent.press(screen.getByRole('button', { name: 'Choose photos' }));
 await fireEvent.press(await screen.findByRole('button', { name: 'Use these photos' }));
 expect(await screen.findByRole('button', { name: 'Remove photo 1' })).toBeTruthy();
 const confirm = jest.spyOn(Alert, 'alert').mockImplementation((_title, _message, buttons) => { buttons?.find(button => ['Create video', 'Discard'].includes(button.text ?? ''))?.onPress?.(); });
 await fireEvent.changeText(await screen.findByLabelText('Opening caption'), 'My best trip');
 await fireEvent.press(screen.getByRole('button', { name: 'Cinema' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Sunset' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Create memory video' }));
 expect(await screen.findByRole('progressbar', { name: 'Creating your video' })).toBeTruthy();
 expect(screen.getByText('Keep Roamie open. Your preview will appear here when it is ready.')).toBeTruthy();
 expect(screen.getByRole('button', { name: 'Cancel video' })).toBeTruthy();
 await act(async () => finishRender(new Uint8Array([1,2,3])));
 expect(await screen.findByRole('button', { name: 'Save video to Photos' })).toBeTruthy();
 expect(screen.queryByRole('progressbar')).toBeNull();
 expect(renderVideo).toHaveBeenCalledWith('Kyoto memories', 60, ['YWJj'], ['A memory'], expect.any(AbortSignal), expect.objectContaining({theme:'cinema',soundtrack:'sunset',openingCaption:'My best trip'}));
 await fireEvent.press(screen.getByRole('button', { name: 'Discard video' }));
 expect(discard).toHaveBeenCalled();
 expect(screen.queryByRole('button', { name: 'Save video to Photos' })).toBeNull();
 expect(screen.getByRole('button', { name: 'Remove photo 1' })).toBeTruthy();
 renderVideo.mockImplementationOnce((_title, _duration, _images, _captions, signal) => new Promise((_resolve, reject) => {
   signal?.addEventListener('abort', () => reject(new Error('Aborted')), {once:true});
 }));
 await fireEvent.press(screen.getByRole('button', { name: 'Create memory video' }));
 expect(await screen.findByRole('progressbar', { name: 'Creating your video' })).toBeTruthy();
 await fireEvent.press(screen.getByRole('button', { name: 'Cancel video' }));
 expect(await screen.findByText('Video cancelled. Your photos and choices are safe.')).toBeTruthy();
 expect(screen.queryByRole('progressbar')).toBeNull();
 expect(screen.getByRole('button', { name: 'Create memory video' })).toBeEnabled();
 renderVideo.mockRejectedValueOnce(new Error('Connection lost. Try again.'));
 await fireEvent.press(screen.getByRole('button', { name: 'Create memory video' }));
 expect(await screen.findByText('Connection lost. Try again.')).toBeTruthy();
 expect(screen.queryByRole('progressbar')).toBeNull();
 expect(screen.getByRole('button', { name: 'Create memory video' })).toBeEnabled();
 expect(screen.getByRole('button', { name: 'Remove photo 1' })).toBeTruthy();
 confirm.mockRestore();
 await fireEvent.press(screen.getByRole('tab', { name: 'Your days' }));
 await fireEvent.press(await screen.findByRole('button', { name: 'Add a stop' }));
 await fireEvent.changeText(screen.getByLabelText('Place or activity'), 'Lunch by the river');
 await fireEvent.press(screen.getByRole('button', { name: 'Save stop' }));
 expect(await screen.findAllByText('Lunch by the river')).toHaveLength(2);
 await fireEvent.press(screen.getByRole('button', { name: 'All trips' }));
 expect(await screen.findByText('Kyoto memories')).toBeTruthy();
 await fireEvent.press(screen.getByRole('button', { name: 'Open Kyoto memories' }));
 expect(await screen.findByRole('button', { name: 'All trips' })).toBeTruthy();
 await fireEvent.press(screen.getByRole('button', { name: 'All trips' }));
 const alert = jest.spyOn(Alert, 'alert').mockImplementation(() => {});
 await fireEvent.press(screen.getByRole('button', { name: 'Delete Kyoto memories' }));
 expect(alert).toHaveBeenCalledWith('Delete this local trip?', expect.any(String), expect.arrayContaining([expect.objectContaining({ text: 'Cancel', style: 'cancel' })]));
 expect(screen.getByText('Kyoto memories')).toBeTruthy();
 alert.mockRestore();
 const writes = jest.mocked(AsyncStorage.setItem).mock.calls.filter(([key]) => key === tripStorageKey('traveller'));
 expect(JSON.parse(writes[writes.length - 1][1])[0].days[3].destination).toBe('Osaka, Japan');
 expect(JSON.parse(writes[writes.length - 1][1])[0].destinationDetails.countryCode).toBe('JP');
 expect(JSON.parse(writes[writes.length - 1][1])[0].preferences).toEqual({styles:['Family'],adults:2,children:1,luggage:2,foodPreferences:['Halal']});
 expect(JSON.parse(writes[writes.length - 1][1])[0].currency).toBe('JPY');
 expect(JSON.parse(writes[writes.length - 1][1])[0].interests).toBe('Gardens');
 expect(JSON.parse(writes[writes.length - 1][1])[0].startDate).toBe(`${future.getFullYear()}-${String(future.getMonth() + 1).padStart(2, '0')}-15`);
 expect(JSON.parse(writes[writes.length - 1][1])[0].days[4].date).toBe(`${future.getFullYear()}-${String(future.getMonth() + 1).padStart(2, '0')}-19`);
 expect(JSON.parse(writes[writes.length - 1][1])[0].days[0].stops[0].title).toBe('Lunch by the river');
}, 20000);
