import { afterEach, expect, jest, test } from '@jest/globals';
import { fireEvent, render, screen } from '@testing-library/react-native';
import { fetch } from 'expo/fetch';
import { Alert } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Trips from '../../app/trips';
import { StoreProvider } from '../store';
import { TripsProvider } from '../trip-store';
import { tripStorageKey } from '../trips';
jest.mock('@react-native-async-storage/async-storage', () => ({ getItem: jest.fn(async () => null), setItem: jest.fn(async () => {}) }));
jest.mock('react-native-safe-area-context', () => ({ useSafeAreaInsets: () => ({ top: 0, bottom: 0, left: 0, right: 0 }) }));
jest.mock('react-native-view-shot', () => ({ captureRef: jest.fn() }));
jest.mock('expo-media-library', () => ({}));
jest.mock('expo-file-system', () => ({ Paths: { document: 'file:///test' }, Directory: class { uri = 'file:///test'; }, File: class {} }));
jest.mock('expo-video', () => ({ useVideoPlayer: jest.fn(), VideoView: () => null }));
jest.mock('expo/fetch', () => ({ fetch: jest.fn() }));
const previousAuth = process.env.EXPO_PUBLIC_AUTH_ENABLED;
afterEach(() => { process.env.EXPO_PUBLIC_AUTH_ENABLED = previousAuth; });
test('traveller creates a trip, adds a timed meal and reopens the saved calendar', async () => {
 process.env.EXPO_PUBLIC_AUTH_ENABLED = 'false';
 jest.mocked(fetch).mockResolvedValue({ ok: true, status: 200, json: async () => [{ placeId:'kyoto', name:'Kyoto', label:'Kyoto, Japan', countryCode:'JP', country:'Japan' }] } as Awaited<ReturnType<typeof fetch>>);
 await render(<StoreProvider accountId="traveller"><TripsProvider accountId="traveller"><Trips /></TripsProvider></StoreProvider>);
 expect(await screen.findByRole('header', {name: 'A little planning. A great adventure.'})).toBeTruthy();
 expect(screen.queryByRole('button', {name: 'New trip'})).toBeNull();
 await fireEvent.press(screen.getByRole('button', { name: 'Plan my first trip' }));
 await fireEvent.changeText(screen.getByLabelText('Trip name'), 'Kyoto memories');
 await fireEvent.press(screen.getByRole('button', { name: 'Departure date: Choose a date' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Next year' }));
 const future = new Date(new Date().getFullYear() + 1, new Date().getMonth(), 15, 12);
 await fireEvent.press(screen.getByRole('button', { name: future.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) }));
 await fireEvent.changeText(screen.getByLabelText('Destination'), 'Kyoto');
 await fireEvent.press(await screen.findByRole('button', { name: 'Kyoto, Japan' }));
 await fireEvent.changeText(screen.getByLabelText('Days at destination 1'), '3');
 await fireEvent.press(screen.getByRole('button', { name: 'Add another destination' }));
 jest.mocked(fetch).mockResolvedValue({ ok: true, status: 200, json: async () => [{ placeId:'osaka', name:'Osaka', label:'Osaka, Japan', countryCode:'JP', country:'Japan' }] } as Awaited<ReturnType<typeof fetch>>);
 await fireEvent.changeText(screen.getByLabelText('Destination 2'), 'Osaka');
 await fireEvent.press(await screen.findByRole('button', { name: 'Osaka, Japan' }));
 await fireEvent.changeText(screen.getByLabelText('Days at destination 2'), '2');
 await fireEvent.press(screen.getByRole('button', { name: 'Currency: USD · US Dollar' }));
 await fireEvent.changeText(screen.getByLabelText('Search Currency'), 'yen');
 await fireEvent.press(screen.getByRole('button', { name: 'JPY · Japanese Yen' }));
 await fireEvent.changeText(screen.getByLabelText('Travellers (1–12)'), '3');
 await fireEvent.press(screen.getByRole('button', { name: 'Trip style, food & luggage' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Family' }));
 await fireEvent.press(screen.getByRole('button', { name: 'Halal' }));
 await fireEvent.changeText(screen.getByLabelText('Children included in your travellers'), '1');
 await fireEvent.changeText(screen.getByLabelText('Bags for the whole group (0–24)'), '2');
 await fireEvent.changeText(screen.getByLabelText('Things you love'), 'Gardens');
 await fireEvent.press(screen.getByRole('button', { name: 'Create my trip' }));
 await fireEvent.press(await screen.findByRole('button', { name: 'Add a stop' }));
 await fireEvent.changeText(screen.getByLabelText('Place or activity'), 'Lunch by the river');
 await fireEvent.press(screen.getByRole('button', { name: 'Save stop' }));
 expect(await screen.findAllByText('Lunch by the river')).toHaveLength(2);
 await fireEvent.press(screen.getByRole('button', { name: 'All trips' }));
 expect(await screen.findByText('Kyoto memories')).toBeTruthy();
 await fireEvent.press(screen.getByRole('button', { name: 'Open Kyoto memories' }));
 expect(await screen.findByRole('button', { name: 'All trips' })).toBeTruthy();
 await fireEvent.press(screen.getByRole('button', { name: 'All trips' }));
 const alert = jest.spyOn(Alert, 'alert').mockImplementation(() => {});
 await fireEvent.press(screen.getByRole('button', { name: 'Delete Kyoto memories' }));
 expect(alert).toHaveBeenCalledWith('Delete this local trip?', expect.any(String), expect.arrayContaining([expect.objectContaining({ text: 'Cancel', style: 'cancel' })]));
 expect(screen.getByText('Kyoto memories')).toBeTruthy();
 alert.mockRestore();
 const writes = jest.mocked(AsyncStorage.setItem).mock.calls.filter(([key]) => key === tripStorageKey('traveller'));
 expect(JSON.parse(writes[writes.length - 1][1])[0].days[3].destination).toBe('Osaka, Japan');
 expect(JSON.parse(writes[writes.length - 1][1])[0].destinationDetails.countryCode).toBe('JP');
 expect(JSON.parse(writes[writes.length - 1][1])[0].preferences).toEqual({styles:['Family'],adults:2,children:1,luggage:2,foodPreferences:['Halal']});
 expect(JSON.parse(writes[writes.length - 1][1])[0].currency).toBe('JPY');
 expect(JSON.parse(writes[writes.length - 1][1])[0].interests).toBe('Gardens');
 expect(JSON.parse(writes[writes.length - 1][1])[0].startDate).toBe(`${future.getFullYear()}-${String(future.getMonth() + 1).padStart(2, '0')}-15`);
 expect(JSON.parse(writes[writes.length - 1][1])[0].days[4].date).toBe(`${future.getFullYear()}-${String(future.getMonth() + 1).padStart(2, '0')}-19`);
 expect(JSON.parse(writes[writes.length - 1][1])[0].days[0].stops[0].title).toBe('Lunch by the river');
}, 20000);
