// Generated by ai-agents/scripts/export_roamie_mobile_contract.py.
export type PlanningBudget = { accommodation_minor: number; food_minor: number; activities_minor: number; transport_minor: number; contingency_minor: number };
export type PlanningDay = { date: string; destination: string; stops: (PlanningStop)[] };
export type PlanningStop = { evidence_id: string; time: string; minutes: number; note: string };
export type TripOption = { tier: "budget" | "balanced" | "premium"; label: string; summary: string; accommodation_ids?: (string)[]; accommodation_guidance: string; transport_guidance: string; budget: PlanningBudget; days: (PlanningDay)[] };
