import { modeName, tripRoute, type Trip } from './trips';
import { format as formatMoney } from './money';

export const escapeHtml = (text: string) => text.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const style = `@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#443451;background:#fcf9fd;font-size:12px;line-height:1.55}h1,h2{font-family:Georgia,serif;color:#765397}h1{font-size:40px;line-height:1.05;margin:12px 0}h2{font-size:22px;margin:0 0 12px}.hero{padding:28px;background:#eee3f4;border:1px solid #dfcde8;border-radius:18px;margin-bottom:24px}.eyebrow{letter-spacing:3px;font-size:10px;color:#775393;text-transform:uppercase}.day{break-inside:avoid;border:1px solid #e2d3e8;border-radius:16px;padding:20px;margin-bottom:18px;background:white}.stop{display:flex;gap:18px;padding:12px 0;border-top:1px solid #f0e7f3}.time{width:58px;flex-shrink:0;color:#79568b;font-weight:bold}.note{color:#6e6076;font-size:11px}.cost{color:#765397;font-weight:bold}.photo{break-inside:avoid;background:white;padding:14px;border:1px solid #e2d3e8;border-radius:8px;margin:0 0 24px}.photo img{max-width:100%;width:100%;height:430px;object-fit:contain}.caption{font-family:Georgia,serif;font-size:16px;margin-top:12px;color:#765397}footer{font-size:10px;color:#796c7f;border-top:1px solid #e3d6e9;padding-top:12px}a{color:#765397}`;
function document(trip: Trip, content: string, subtitle: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${style}</style></head><body><div class="hero"><div class="eyebrow">Roamie · ${subtitle}</div><h1>${escapeHtml(trip.title)}</h1><p>${escapeHtml(tripRoute(trip))} · ${escapeHtml(trip.startDate)} — ${escapeHtml(trip.endDate)}</p><div class="note">${trip.days.length} days · ${trip.travellers} traveller${trip.travellers === 1 ? '' : 's'} · A little adventure, a lot to remember.</div></div>${content}<footer>Made with Roamie · Keep the moments that matter.</footer></body></html>`;
}
export function itineraryHtml(trip: Trip): string {
  return document(trip, trip.days.map((day, i) => `<section class="day"><div class="eyebrow">Day ${i + 1}</div><h2>${escapeHtml(day.date)}</h2><p>${escapeHtml(day.destination ?? trip.destination)}</p>${day.stops.length ? day.stops.map(stop => `<div class="stop"><div class="time">${escapeHtml(stop.time)}<br><span class="note">${stop.minutes} min</span></div><div><strong>${escapeHtml(stop.title)}</strong><div class="note">${escapeHtml(stop.kind)} · ${escapeHtml(stop.note)}</div>${stop.place ? `<div class="note">${escapeHtml(stop.place.address)} · Source: Google Maps</div>` : ''}<div class="cost">Est. ${escapeHtml(formatMoney(stop.costMinor, trip.currency))}</div>${stop.transport.length ? `<div class="note">Travel options (estimates): ${stop.transport.map(t => `${modeName[t.mode]} ${t.minutes ? `${t.minutes} min · ${formatMoney(t.costMinor, trip.currency)}` : 'check availability'} — ${escapeHtml(t.note)}`).join('<br>')}</div>` : ''}</div></div>`).join('') : '<p>A little room for spontaneity. Add your plans here.</p>'}</section>`).join('') + `<p class="note">${escapeHtml(trip.notice)}</p>`, 'Your trip, day by day');
}
export function albumHtml(trip: Trip, photos: { data: string; caption: string }[]): string {
  if (photos.length < 1 || photos.length > 15 || photos.some(p => p.data.length > 700000 || !/^[A-Za-z0-9+/]+=*$/.test(p.data))) throw new Error('Choose 1–15 valid photos.');
  return document(trip, photos.map((photo, i) => `<figure class="photo"><img src="data:image/jpeg;base64,${photo.data}" alt="Trip photo ${i + 1}"><figcaption class="caption">${escapeHtml(photo.caption || `Memory ${i + 1}`)}</figcaption></figure>`).join(''), 'Collected moments');
}
